name: SymptomTrajectories
channels:
  - pytorch
  - nvidia
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.11
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - numpy=1.26.*
  - pandas=2.2.*
  - scikit-learn
  - tqdm
  - matplotlib
  - seaborn
  - pyyaml
  - pip